# REINVENT4 TOML input example for transfer learning
#
# Focus a given model towards a set of input SMILES.  This can also be used to
# start from scratch from and an untrained prior.


run_type = "transfer_learning"
device = "mps"  # set torch device e.g. "cpu"
tb_logdir = "vegfr"  # name of the TensorBoard logging directory
json_out_config = "json_transfer_learning_10.json"  # write this TOML to JSON

[parameters]

num_epochs = 100  # number of steps to run
save_every_n_epochs = 10 # save checkpoint model file very N steps
batch_size = 50
num_refs = 100  # number of reference molecules randomly chosen for similarity
               # set this to zero for large datasets (>200 molecules)!
sample_batch_size = 100  # number of sampled molecules to compute sample loss
# Uncomment one of the comment blocks below.  Each generator needs a model
# file and possibly a SMILES file with seed structures.

## Reinvent
input_model_file = "../priors/reinvent.prior"

smiles_file = "example.smi"  # read 1st column
output_model_file = "TL_vegfr_reinvent_10.model"
validation_smiles_file = "example.smi" 

# Define the type of similarity and its parameters
pairs.type = "tanimoto"
pairs.upper_threshold = 1.0
pairs.lower_threshold = 0.7
pairs.min_cardinality = 1
pairs.max_cardinality = 199